-- CreateTable
CREATE TABLE "userOTP" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "expired" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "userOTP_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "userOTP" ADD CONSTRAINT "userOTP_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
